raw_data:
  folder_path: data
  num_files: 2

minio_datalake:
  endpoint: localhost:9001
  bucket_name: bronze-data  
  folder_name: raw_data
  access_key: minio_access_key
  secret_key: minio_secret_key

minio_lakehouse:
  endpoint: localhost:9002
  bucket_name: silver-data  
  folder_name: raw_data
  access_key: minio_access_key
  secret_key: minio_secret_key